--- #YAML:1.0
name:               Working-Daemon
version:            0.29
abstract:           Perl extension for blah blah blah
author:
    - Artur Bergman <sky+cpan@crucially.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
